export const restaurants = [
    {
        id: 1,
        image: "/images/resto1.png",
        name: "The House1",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 2,
        image: "/images/resto1.png",
        name: "The House2",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 3,
        image: "/images/resto1.png",
        name: "The House3",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 4,
        image: "/images/resto1.png",
        name: "The House4",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 5,
        image: "/images/resto1.png",
        name: "The House5",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 6,
        image: "/images/resto1.png",
        name: "The House6",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 7,
        image: "/images/resto1.png",
        name: "The House7",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 8,
        image: "/images/resto1.png",
        name: "The House8",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 9,
        image: "/images/resto1.png",
        name: "The House9",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 10,
        image: "/images/resto1.png",
        name: "The House10",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 11,
        image: "/images/resto1.png",
        name: "The House11",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 12,
        image: "/images/resto1.png",
        name: "The House12",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 13,
        image: "/images/resto1.png",
        name: "The House13",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 14,
        image: "/images/resto1.png",
        name: "The House14",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
    {
        id: 15,
        image: "/images/resto1.png",
        name: "The House15",
        category: "Pastas",
        score: 4,
        priceRange: "€€€",
        distance: 1000.1,
        hours: ["18:00", "19:00", "20:00"],
        featured: true,
    },
];

export const reservations = [
    {
        id: 1,
        image: "/images/resto2.png",
        title: "1Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 2,
        image: "/images/resto2.png",
        title: "2Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 3,
        image: "/images/resto2.png",
        title: "3Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 4,
        image: "/images/resto2.png",
        title: "4Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 5,
        image: "/images/resto2.png",
        title: "5Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 6,
        image: "/images/resto2.png",
        title: "6Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 7,
        image: "/images/resto2.png",
        title: "7Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 8,
        image: "/images/resto2.png",
        title: "8Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 9,
        image: "/images/resto2.png",
        title: "9Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
    {
        id: 10,
        image: "/images/resto2.png",
        title: "10Pizza y pastas ricas y clásicas de Italia a la esquina de la vuelta de tu casa",
        seller: {
            image: "/images/avatar.png",
            name: "Matias",
        },
        price: "Є200",
        hours: "19 hs.",
        paymentType: "pago no incluido",
    },
];
